### ISSUE TITLE
Plugin Does Not Generate Worlds And Commands Do Not Work

### ISSUE THREAD

**Issue by hi00ih** [kitskub/bSpace#46]
Plugin is installed correctly. Attempted on RB of craftbukkit as well as several other builds, the plugin says [INFO] [BananaSpace] Enabled version 1.4 at startup but nothing else. Commands in game do not work, and there is no world_space or any new world.

**Comment by iffa** [comment]
Do you have Multiverse?

**Comment by kitskub** [comment]
Did you put a world in the config?

**Comment by hi00ih** [comment]
I have tried with and without multiverse. I can generate a world useing multiverse's commands but then i do not get the features such as having to wear a spacesuit, which i want. I have the default world in the config that i removed the comments from.

**Comment by kitskub** [comment]
Ok, can you post your config.yml please?

**Comment by kitskub** [comment]
Fixed in latest changes

**Comment by hi00ih** [comment]
Sorry i didn't get to post my config. Thanks for fixing it, will test now.

**Comment by hi00ih** [comment]
Nope still doesn't work.
World does not generate and commands do not work in-game. No errors. And the commands do not show unknown command either.

Config.yml: http://pastebin.com/kDWCUimv

**Comment by iffa** [comment]
Any errors?

**Comment by hi00ih** [comment]
None at all.
Says:
 [INFO] [BananaSpace] Generated configuration file for version 1.4_1
 [INFO] [BananaSpace] Generated planet configuration for version 1.4_1
9 [SEVERE] [BananaSpace] Your configuration file has no worlds! Cancelling world generation process.

The first time and then when i set up the config exactly like the one i put on pastebin, simply says
[INFO] [BananaSpace] Enabled version 1.4_1
With no world generated. The commands in game and in console do nothing at all not even give me unknown command

> space
> space help

**Comment by iffa** [comment]
If you have Multiverse enabled, disable it.

**Comment by hi00ih** [comment]
Ok, that worked. I was able to generate the world and enter it no problem. My live server however does use multiverse, is there any way around this?

**Comment by iffa** [comment]
1.5 is your best bet.

**Comment by hi00ih** [comment]
Yep alright. Waiting on that then. Thanks for the help in the meantime.

**Comment by kitskub** [comment]
Why isn't multiverse allowing it?

**Comment by iffa** [comment]
if multiverse is enabled commands odnt work

**Comment by hi00ih** [comment]
And the worlds don't generate.

**Comment by iffa** [comment]
yes

**Comment by kitskub** [comment]
Yes, but what part about it is stopping it?
