### ISSUE TITLE
Death

### ISSUE THREAD

**Issue by kripts** [kitskub/bSpace#78]
I created the space world. did the settings so you need to wear a helmet, couldn't get it working, then all a sudden I start dieing, I then died and respawned in default world and now I cant stop dieing in the default world. helmet or no helmet :P

**Comment by kitskub** [comment]
Ok, this was an issue that was thought to be solved. I'll take another look.

**Comment by kripts** [comment]
also it doesnt seem to be registering the helmet I set as if I put one on it still kills me?

**Comment by kitskub** [comment]
I believe i know what is causing this. I had previously assumed that respawn counts as a teleport. It doesn't. Should have a fix very soon.

**Comment by kitskub** [comment]
Again, just check the target directory. Haven't checked jenkins. Tell me if it works...

**Comment by kripts** [comment]
Ill be checking once I get in, Thanks for the quick response

**Comment by kripts** [comment]
I cant seem to die if I dont wear a helmet now like its not set to kill me still get damaged from falling and somehow when i jump out of water?

**Comment by kripts** [comment]
Also the helmet give command gives you it in the wrong world so if you set diamond helmet then when you die in space you get a diamond helmet in default world

**Comment by kitskub** [comment]
Same deal as last time. Target directory blah blah. Jenkins isn't working.... Tell me what happens. Thanks.

**Comment by kripts** [comment]
My sever now keeps restarting everytime I log in with this update so I cant even get onto the world

**Comment by kitskub** [comment]
Can you post the last few lines of your server.log file?  Just enough for the last restart.

**Comment by kripts** [comment]
2011-12-11 04:33:30 [INFO] [35m[Server] Welcome back, Kripts[0m
2011-12-11 04:33:30 [INFO] [CONSOLE->Kripts] Welcome, Kripts
2011-12-11 04:33:30 [INFO] [CONSOLE->Kripts] To KriptsKraft We currently have 1 players online
2011-12-11 04:33:33 [WARNING] Can't keep up! Did the system time change, or is the server overloaded?
2011-12-11 04:33:43 [INFO] WorldGuard: (space) Single session is enforced.
2011-12-11 04:33:43 [INFO] WorldGuard: (space) TNT ignition is blocked.
2011-12-11 04:33:43 [INFO] WorldGuard: (space) Lighters are PERMITTED.
2011-12-11 04:33:43 [INFO] WorldGuard: (space) Lava fire is blocked.
2011-12-11 04:33:43 [INFO] WorldGuard: (space) All fire spread is disabled.
2011-12-11 04:33:43 [INFO] WorldGuard: Loaded configuration for world 'space"
2011-12-11 04:33:43 [WARNING] WorldGuard: Region file for world "space" missing or inaccessible.
2011-12-11 04:33:43 [SEVERE] java.lang.NullPointerException
2011-12-11 04:33:43 [SEVERE]    at com.sk89q.worldguard.bukkit.FlagStateManager.run(FlagStateManager.java:88)
2011-12-11 04:33:43 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2011-12-11 04:33:43 [SEVERE]    at java.lang.Thread.run(Thread.java:636)
2011-12-11 04:33:43 [SEVERE] Could not pass event CUSTOM_EVENT to bSpace
java.lang.IllegalArgumentException: Plugin cannot be null
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:200)
    at me.iffa.bspace.listeners.SpaceSuffocationListener.onAreaLeave(SpaceSuffocationListener.java:45)
    at me.iffa.bspace.api.event.area.SpaceAreaListener.onCustomEvent(SpaceAreaListener.java:54)
    at org.bukkit.plugin.java.JavaPluginLoader$97.execute(JavaPluginLoader.java:945)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at me.iffa.bspace.listeners.SpacePlayerListener.onPlayerMove(SpacePlayerListener.java:163)
    at org.bukkit.plugin.java.JavaPluginLoader$7.execute(JavaPluginLoader.java:307)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:181)
    at net.minecraft.server.Packet10Flying.a(SourceFile:126)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-12-11 04:33:43 [INFO] Kripts lost connection: user was kicked.
2011-12-11 04:33:43 [INFO](Kripts): Kicked with: Server is restarting
2011-12-11 04:33:43 [INFO](Kripts): Redirect detected: null

Hope this helps, i didnt see your message before sorry

**Comment by kitskub** [comment]
Ok, I fixed the nullpointerexception, so test the latest for that...That might fix the server restarting...

**Comment by kripts** [comment]
Server doesnt restart now but still no death in space :(

**Comment by kitskub** [comment]
Hmm. Ok. Let me take another look

**Comment by kitskub** [comment]
Let's see if that works

**Comment by kripts** [comment]
Well good news it half works, but only the first time you enter the world, so if you join the server and go the space world it will kill you, if you return to the world after death it will not, unless you log out and back in? Still have the mass death glitch when you jump off into the void though.Thanks for all your help again

**Comment by kitskub** [comment]
Hmm. Ok, new info. Now what is this death glitch?

**Comment by kripts** [comment]
if you fall to the void you die like 20 times before respawning

**Comment by kitskub** [comment]
Hmm....ok. That should be an easy fix...

**Comment by kitskub** [comment]
Ok, try that.

**Comment by kripts** [comment]
Okay, The return to space still glitches once you have already been to space and died you still need to relog, But the good news is that the mass death caused by falling off the world is fixed.

**Comment by kitskub** [comment]
It's still not working? Hmm, I tested it myself this time and it worked for me. Can you describe what exactly you are doing?

**Comment by kripts** [comment]
I enter the world with /mvtp space (which is the name of the world with the generator) It then starts to kill me if I do not have the punkin on my head. If I do die I then spawn back in the default world, If I then return to space using /mvtp space, I wont die without the pumkin on my head, but if I log out and back on, health starts to decrease.

**Comment by kripts** [comment]
It still doesnt seem to work, try joining my server to test for yourself (kriptskraft.co.uk)

**Comment by kitskub** [comment]
Hmm, I might do that when I get home. Even if I'm not fixing your error, I keep preventing other ones

**Comment by kitskub** [comment]
I'll check again though

**Comment by kripts** [comment]
Im on the server now, if you arn't busy

**Comment by kripts** [comment]
Nope, still only works once then you need to relog, now endermen are getting damaged for some reason? Thanks for all your work you are doing :)

**Comment by kitskub** [comment]
Found the single line that is probably causing all this trouble...

**Comment by kitskub** [comment]
Got it. And this error dates back all the way. Bukkit.getScheduler().isCurrentlyRunning() != Bukkit.getScheduler().isQueued()!!!!! Fixing now

**Comment by kripts** [comment]
Well you dared me... Still doesn't work :P come on my server and check for yourself

**Comment by kitskub** [comment]
Really? Dang it.
